export enum SelectedContent {
  LONG_WAIT_TIME_FOR_REATMENT = 'LONG_WAIT_TIME_FOR_REATMENT',
  LONG_WAIT_TIME_FOR_CONSULTATION = 'LONG_WAIT_TIME_FOR_CONSULTATION',
  LONG_WAIT_TIME_FOR_MEDICATION = 'LONG_WAIT_TIME_FOR_MEDICATION',
  POOR_DOCTOR_ATTITUDE = 'POOR_DOCTOR_ATTITUDE',
}
