export enum TimePeriodType {
  MORNING_SESSION = 'MORNING_SESSION',
  AFTERNOON_SESSION = 'AFTERNOON_SESSION',
  EVENING_SESSION = 'EVENING_SESSION',
}

export enum GenderType {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  NON_BINARY = 'NON_BINARY',
}

export enum TreatmentType {
  ACUPUNTURE_TREATMENT = 'ACUPUNTURE_TREATMENT',
  MEDICINE_TREATMENT = 'MEDICINE_TREATMENT',
  BOTH_TREATMENT = 'BOTH_TREATMENT',
  NO_TREATMENT = 'NO_TREATMENT',
}
